- name: downloads package
  get_url: url=http://s3.amazonaws.com/influxdb/influxdb_0.9.2.1_amd64.deb dest=/var/local/influxdb_0.9.2_amd64.deb

- name: installs package
  command: dpkg -i /var/local/influxdb_0.9.2.1_amd64.deb creates=/etc/init.d/influxdb

- name: adds influxdb conf
  template: src=influx.conf dest=/etc/opt/influxdb/influxdb.conf force=true
  notify: restart influxdb

- name: configures logrotate
  template: src=logrotate.j2 dest=/etc/logrotate.d/app mode=644
