---
- hosts: database
  become: true
  roles:
    - postgresql-server

- hosts: web
  become: true
  vars:
    ruby_version: 2.6.3
  roles:
    - git
    - yarn
    - postgresql-client
    - rails
    - puma
    - nginx
