- name: installs sidekiq
  command: gem install sidekiq creates=/usr/local/bin/sidekiq

- name: adds sidekiq systemd script
  template: src=sidekiq.service.j2 dest=/etc/systemd/system/sidekiq.service mode=755

- name: reload systemd
  command: systemctl daemon-reload

- name: enable sidekiq service
  command: systemctl enable sidekiq.service

- name: start sidekiq service
  command: systemctl start sidekiq.service
