- name: installs puma
  command: gem install puma creates=/usr/local/bin/puma

- name: adds puma app conf
  template: src=puma.rb.j2 dest={{ app_path }}/config/puma.provisioned.rb mode=644
  notify: restart puma

- name: creates puma pid folder
  file: path={{app_path}}/tmp/pids owner={{user}} group={{user}} state=directory

- name: adds puma systemd script
  template: src=puma.service.j2 dest=/etc/systemd/system/puma.service mode=755

- name: reload systemd
  command: systemctl daemon-reload

- name: enable puma service
  command: systemctl enable puma.service

- name: start puma service
  command: systemctl start puma.service
